name: Build and Update Service

on:
  push:
    branches: [master]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-1

jobs:

  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: docker build -t hello:$(git rev-parse --short HEAD) --target app .

      - name: Docker Auth
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS \
          --password-stdin 303981612052.dkr.ecr.eu-west-1.amazonaws.com

      - name: Docker Push
        run: |
          docker tag hello:$(git rev-parse --short HEAD) \
          303981612052.dkr.ecr.eu-west-1.amazonaws.com/hello:$(git rev-parse --short HEAD)
          docker push 303981612052.dkr.ecr.eu-west-1.amazonaws.com/hello:$(git rev-parse --short HEAD)

  update-service:
    name: Update ECS service
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2

      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -var task_image_tag=$(git rev-parse --short HEAD) -auto-approve